---
title: "Cp3_assignment_1_instructions"
author: "Aidan O'Hara"
date: "2023-08-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Factorial, Fibonacci, and Foobar examples

# Exercise 1

Re-create the factorial function, `factorial()` without calling the factorial function. Think about what inputs are appropriate for your function, and have your function return the " Error " string if provided an invalid input.


# Exercise 2

Write a function that returns a vector of the first n elements of the fibonacci sequence, starting with 0,1,...


# Exercise 3

Write a function called `fooBarFun` that takes a number for an input, if the number is divisible by 3 the function should return the string "Foo", if the number is divisible by 5 the function should return the string "Bar".  Finally if the number is divisble by both 3 and 5 the function should return the string "FooBar".  Return an empty string if the number is not divisble by 3 or 5.  Use `%%` to check for divisibility and `paste0` to construct your string returns.
